name: test-macOS

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
  push:
    branches:
      - master
      - main
      - canary
      - v[0-9]+.x-staging
      - v[0-9]+.x
    paths-ignore:
      - 'doc/**'

env:
  PYTHON_VERSION: 3.9
  FLAKY_TESTS: dontcare

jobs:
  test-macOS:
    if: github.event.pull_request.draft == false
    runs-on: macos-latest
    steps:
      - name: Install ccache
        run: |
          brew update
          brew install ccache
          echo "CCACHE_DIR=/tmp/nodejs-ccache" >> $GITHUB_ENV
          echo "CCACHE_MAXSIZE=500M" >> $GITHUB_ENV
      - name: Initialize Compiler Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: /tmp/nodejs-ccache
          key: cache-${{ runner.os }}-${{ github.sha }}
          restore-keys: cache-${{ runner.os }}-
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: |
          ccache -s
          npx envinfo
      - name: Build
        run: |
          export PATH="/usr/local/opt/ccache/libexec:$PATH"
          make build-ci -j2 V=1 CONFIG_FLAGS="--error-on-warn"
          ccache -s
      - name: Test
        run: make run-ci -j2 V=1 TEST_CI_ARGS="-p actions"
